version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@next # force install next version to test electron-builder
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run release

test: off

branches:
    only:
        - master

deploy:
- provider: BinTray
  username: emaknyus
  api_key:
    secure: d6638fc364c86e065f38e702b14b8d7d6587de25
  subject: badai
  repo: baper
  package: mypackage
  version: version
  publish: true
  override: true
  explode: true
